config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :trips do
    member do
      patch :preferences
      get :details
      patch :save
      get :mistery
      patch :change_mistery
    end
    resources :steps, only: ['create', 'new']
  end
  resources :steps, only: ['index', 'show']
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :arrival_city, class_name: 'City'
  belongs_to :departure_city, class_name: 'City'
  belongs_to :user, optional: true
  has_many :steps, dependent: :destroy
  validates :departure_city, :arrival_city, :start_date, :end_date, presence: true
end

app/controllers/trips_controller.rb
require 'json'
require 'open-uri'

class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :mistery, :show, :create, :change_mistery]
  def index
    @trips = Trip.where(user: current_user)
  end

  def new
    @trip = Trip.new
    @step = Step.new
  end

  def create
    @trip = Trip.new(trip_params)
    redirect_to new_trip_step_path(@trip) if @trip.save!
  end

  def show
    @trip = Trip.find(params[:id])
    @list_acti_map = []
    @trip.steps.each do |step|
      @list_acti_map << step.activities
    end
    response = ordonated_steps(@trip)
    steps_to_map(response, false)
  end

  def ordonated_steps(trip)
    order_steps = []
    trip.steps.each do |step|
      if step.city_id == trip.departure_city_id
        order_steps.prepend(step)
      elsif step.city_id == trip.arrival_city_id
        next
      else
        order_steps << step
      end
    end
    #first and last city need to be at begining and end for API optimize call
    order_steps << trip.steps.find{|step| step.city_id == trip.arrival_city_id }
    steps_coord = ""
    order_steps.each do |step|
      steps_coord += step.city.longitude.to_s + ',' + step.city.latitude.to_s + ';'
    end
    steps_call = steps_coord.delete_suffix(";")
    url = "https://api.mapbox.com/optimized-trips/v1/mapbox/driving/#{steps_call}?source=first&destination=last&steps=true&access_token=#{ENV['MAPBOX_API_KEY']}"
    response_serialized = open(url).read
    return response = JSON.parse(response_serialized)
  end

  def steps_to_map(response, details)
    steps = response['waypoints'].sort_by! { |waypoint| waypoint['waypoint_index'] }
    i = -1
    @markers = steps.map do |step|
      leg = response["trips"][0]["legs"][i]
      this_step = @trip.steps.find{ |st| step['location'][0].round(2) == st.city.longitude.round(2) }
      this_step.distance_next_step = (response["trips"][0]["legs"][i]['distance']/1_000).round(2)
      this_step.save
      i += 1
      # define the order of the trip steps
      step_to_order = @trip.steps.where(id: this_step.id).first
      step_to_order.order = i
      step_to_order.save!
      {
        infoWindow: render_to_string(partial: "infowindow", locals: { step: this_step, api_step: leg, trip: Trip.find(params[:id]), infos: details }),
        lat: step['location'][1],
        lng: step['location'][0]
      }
    end
  end

  def activities_to_map(activities)
    # .select {|item| !(item[:lat].nil? || item[:long].nil?)}.
    @markers = activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end
  end

  def filter_activities_by_time(criteria)
    order_list = order_by_ranking(@activities, criteria)
    total_list = total_duration(order_list)
    list_acti = []
    if total_list < @ratio_type_activities[criteria]
      list_acti << order_list
      list_acti.flatten!
      return list_acti
    else
      order_list.each do |acti|
        return list_acti if (total_duration(list_acti) + acti.duration) > @ratio_type_activities[criteria]
        list_acti << acti
      end
    end
  end

  def activities_in_zone(trip)
    long_max = [trip.arrival_city.longitude, trip.departure_city.longitude].max
    long_min = [trip.arrival_city.longitude, trip.departure_city.longitude].min
    lat_max = [trip.arrival_city.latitude, trip.departure_city.latitude].max
    lat_min = [trip.arrival_city.latitude, trip.departure_city.latitude].min
    activities = Activity.where('longitude BETWEEN ? AND ?', long_min - 0.5, long_max + 0.5).where('latitude BETWEEN ? AND ?', lat_min - 0.5, lat_max + 0.5)
    return activities
  end

  def ratio_duration(trip)
    # calculates ratio of duration of each criteria vs total duration of trip activity
    total_trip_duration = ((trip.end_date - trip.start_date) / 86_400) * 8 * 60 # -> nb days * 8h * 60min
    criteria_sum = trip.criteria["beach"].to_f + trip.criteria["visit"].to_f + trip.criteria["culture"].to_f + trip.criteria["sport"].to_f
    beach_ratio = (total_trip_duration * trip.criteria["beach"].to_f) / criteria_sum
    visit_ratio = (total_trip_duration * trip.criteria["visit"].to_f) / criteria_sum
    culture_ratio = (total_trip_duration * trip.criteria["culture"].to_f) / criteria_sum
    sport_ratio = (total_trip_duration * trip.criteria["sport"].to_f) / criteria_sum

    ratio_duration = { "beach" => beach_ratio, "visit" => visit_ratio, "culture" => culture_ratio, "sport" => sport_ratio }
    @total_trip_duration = total_trip_duration
    return ratio_duration
  end

  def order_by_ranking(array, type)
    result = array.select do |array_act|
      array_act.activity_types == type
    end
    result.sort_by!{|act| act.ranking_interest }
    return result
  end

  def total_duration(array)
    sum = 0
    array.each do |act|
      sum += act.duration
    end
    return sum
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def preferences
    @trip = Trip.find(params[:id])
    @trip.steps.each do |step|
      step.step_activities.each do |step_act|
        if step_act.activity.activity_types == "party"
          StepActivity.destroy(step_act.id)
        end
      end
    end
    @trip.criteria['party'] = params['trip']['criteria']['party']
    count = 0
    @trip.steps.each do |step|
      count += step.duration
    end
    trip_cities = []
    nb_party = count * (@trip.criteria['party'].to_i)/100.round
    good_parties = order_by_ranking(Activity.all, "party")
    @trip.steps.each do |step|
      trip_cities << step.city
    end
    good_parties_good_city = good_parties.reject{|party| !trip_cities.include?party.city }
    good_parties_good_city.first(nb_party).each do |party|
      step_party = @trip.steps.find_by(city: party.city)
      StepActivity.create!(step: step_party, activity: party)

    end
    if @trip.save
      redirect_to details_trip_path(@trip)
    else
      render :edit
    end
  end

  def order_by_ranking(array, type)
  result = array.select do |array_act|
    array_act.activity_types == type
  end
  result.sort_by!{|act| act.ranking_interest }
  return result
  end


  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to new_trip_step_path(@trip)
    else
      render :edit
    end
  end

  def details
    @trip = Trip.find(params[:id])
    @step = Step.new
    list = activities(@trip)
    response = ordonated_steps(@trip)
    steps_to_map(response, true)
  end

  def activities(trip)
    trip_activities = []
    trip.steps.each do |step|
      trip_activities << step.activities
    end
    trip_activities.flatten!
    return trip_activities
  end

  def save
    @trip = Trip.find(params[:id])
    @trip.user = current_user if current_user.present?
    redirect_to(trips_path, alert: 'Trip was successfully saved') if @trip.save!
  end

  def mistery
    # display of mistery choice
    @trip = Trip.find(params[:id])
  end

  def change_mistery
    # 1 step -  update percentage of mistery in trip
    @trip = Trip.find(params[:id])
     @trip.update(trip_params)
     # 2 step -  put all step acti at false
     @trip.steps.each do |step|
      step.step_activities.each do |step_activity|
        step_activity.mistery = false
        step_activity.save
      end
     end
      # 2 step -  number of all activities in the trip
      @nb_all_activities_trip = 0
      @trip.steps.each do |step|
        @nb_all_activities_trip += step.step_activities.count
      end
      # 3 step -  total number of activities to hide
      @nb_all_activities_trip_hide = @nb_all_activities_trip * @trip.percentage_of_mistery / 100
      # 4 step - hide activities in steps

      @trip.steps.each do |step|
        #make visible if step has only one activity
        if step.step_activities.count == 1 && @trip.percentage_of_mistery != 100
          step.step_activities.first.mistery = false
        else
          # create a list of step activities
        activities_in_step_ids = []
        step.step_activities.each do |step_activity|
          activities_in_step_ids << step_activity.id
        end
        # number of activities in step
        nb_all_activities_step = step.step_activities.count
        # percentage of activities in step from total activities of trip
        percentage_activities_in_step = nb_all_activities_step * 100 / @nb_all_activities_trip
        # nb of activities to hide in step
        nb_all_activities_step_hide = (@nb_all_activities_trip_hide * percentage_activities_in_step / 100.to_f).ceil

        # nb of activities to hide times
        nb_all_activities_step_hide.times do
          # choose one activity from step random
          activity_sample = activities_in_step_ids.sample
          # find activity in step activities
          step_activity = StepActivity.find(activity_sample)
          # mistery is true
          step_activity.mistery = true
          step_activity.save
          # delete this activity from the list of all activities in step
          activities_in_step_ids.delete(activity_sample)
        end
      end
        end

      if user_signed_in?
        redirect_to details_trip_path(@trip)
      else
        redirect_to trip_path(@trip)
      end

  end

  private

  def trip_params
    params.require(:trip).permit(:departure_city_id, :arrival_city_id, :start_date, :end_date, :percentage_of_mistery, criteria: {})
  end
end

app/views/trips/_infowindow.html.erb
<div>
  <div style="padding: 10px;">
    <h6 style ="font-size: 14px; font-weight: 600; margin: 0; color: #454D66;"> <%= step.city.name %> - </i> <% if step.duration > 0 %><%= pluralize(step.duration, 'day') %> <% else %> <%= '< 1 day' %> <% end %></h6>
    <% if trip.departure_city != step.city %>
    <p style = "ont-weight: 500;
    color: #575F75;
    font-family: 'Raleway', ‘Montserrat’, sans-serif;
    font-size: 12px;
    opacity: 1;"><%= step.city.name %> - next step<%#= Step.find_by_order(step.order - 1).city.name %> : <%= (api_step['distance']/1_000).round(2) %> km</p>
    <% else %>
    <br>
    <% end %>
    <% if infos == true %>
    <a class= "card-link" href="#<%= step.city.name %>" style="color: #57b894;">View details...</a>
<% end %>
  </div>
</div>

app/views/trips/details.html.erb
<div class="mb-4">
  <h2 class="trip-header text-center mb-5 ">Discover your Trip</h2>


    <!------------------------------------- filters  -------------------------------->
      <div class="preferences d-flex justify-content-center">
 <div class="mb-4 mt-2">
 <p class="filter"><i class="fas fa-umbrella-beach"></i></p>
    <p class="filter mb-4 mt-2">Beach <%= @trip.criteria["beach"] %>%</p>
  </div>
  <div class="mb-4 mt-2">
    <p class="filter"><i class="fas fa-football-ball"></i></p>
    <p class="filter mb-4 mt-2">Sport <%= @trip.criteria["sport"] %>%</p></div>
   <div class="mb-4 mt-2">
    <p class="filter"><i class="fas fa-graduation-cap"></i></p>
  <p class="filter mb-4 mt-2">Culture <%= @trip.criteria["culture"] %>%</p></div>
  <div class="mb-4 mt-2" >
    <p class="filter"><i class="fas fa-camera"></i></p>
  <p class="filter mb-4 mt-2">Visit <%= @trip.criteria["visit"] %>%</p>  </div>
</div>

  <!------------------------------------- end filters  -------------------------------->

  <!------------------------------------- Timeline  -------------------------------->

  <div class="mb-6 timeline-cities d-flex justify-content-between align-items-center">
    <% @trip.steps.order(:order).reverse().each do |step| %>
    <h2><%= step.city.name %></h2>
    <% end %>
  </div>
  <div class="timeline-container d-flex justify-content-around align-items-center mb-5">
    <% counter = 0 %>
    <% @trip.steps.order(:order).reverse().each do |step| %>
    <p class="timeline"><%= counter += 1 %></p>
    <% if step.city != @trip.steps.order(:order).reverse().last.city %>
    <hr>
    <!-- <div class="d-flex justify-content-center align-items-center"> -->
      <span class='text-center '>
    <span class="d-flex car-span-size"><%= step.distance_next_step %> km </span>
        <i class="fas fa-car car-icon"></i>

    </span>

    <hr>
    <% end %>
    <% end %>
  </div>

  <!-------------------------------------- MAP ------------------------------------->

  <div class="d-flex justify-content-around ml-6 mr-6 sticky-map-trip">
    <div class="map sticky-top ">
      <div class="d-flex justify-content-end btn-save">
        <%= link_to "Save", save_trip_path(@trip), method: :patch, class:'green-btn' %>
      </div>
      <div
        id="map"
        style="width: 100%;
        height: 100%;
        zoom: 1.5;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        <!-- appel modal 1 -->
        <div class="d-flex justify-content-center btn-preferences">
          <div class="green-btn mx-2" id="btn-preferences" data-toggle="modal" data-target="#exampleModal"> Preferences</div>

        <!-- appel modal 2 -->

          <div class="green-btn" id="btn-preferences" data-toggle="modal" data-target="#exampleModal2"> Personnalize</div>
        </div>
      </div>
    </div>
  <!------------------------------- activity list  -------------------------------->
    <div class="list-activity">
      <h3 class="trip-header text-center mb-4">Trip's details</h3>
      <% counter = 0 %>
      <% @trip.steps.order(:order).reverse().each do |step| %>
      <div class="d-flex justify-content-center align-items-center mb-4">
        <div style="display: flex; align-items: center; justify-content: center;">
          <p class="timeline-details"><%= counter += 1 %></p>
        </div>
        <p class="city-name text-center"><%= step.city.name %> - <% if step.duration > 0 %><%= pluralize(step.duration, 'day') %> <% else %> <%= '< 1 day' %> <% end %></p>
      </div>
      <%= link_to step_path(step), class:'details-links' do%>
      <% step.step_activities.reverse.each do |step_activity| %>
      <% if step_activity.mistery %>
      <div class="card-product">
        <%=image_tag 'locked3.png', class:'locked'%>
        <div class="card-product-infos">
          <h2>Locked</h2>
          <p>You will discover this activity the day before</p>
        </div>
      </div>
      <% else %>
      <div class="card-product">
        <%=image_tag(step_activity.activity.photo) %>
        <div class="card-product-infos">
          <h2><%= step_activity.activity.name %></h2>
          <p><i class="far fa-clock"></i>About :
            <% if step_activity.activity.duration % 60 == 0 %>
              <%= step_activity.activity.duration/60 %>h</p>
            <% elsif step_activity.activity.duration/60 < 1 %>
              <%= step_activity.activity.duration %>min</p>
              <% else %>
              <%= step_activity.activity.duration/60 %>h <%= step_activity.activity.duration % 60 %>min</p>
            <% end %>

          <p class="green">View details ...</p>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>

  <!------------------------------- End activity list  -------------------------------->

  <!-- début modal  -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
        <div class="text-center trip-header-new">Update your preferences</div>
        </h5>
      </div>
      <div class="modal-body">
        <div class="form-container-criteria-slider" id="preferences" >
          <div class="d-flex justify-content-center ">
            <div class="col-md-7 ">
              <%= simple_form_for@trip do |f| %>
                <div class="form-group  form-control-label">
                  <label for="beach" class="d-flex justify-content-around">Beach</label>
                  <input type="range" class="custom-range" name="trip[criteria][beach]" min="0" max="100" step="1" id="beach" >
                </div>
                <div class="form-group  form-control-label">
                  <label for="sport" class="d-flex justify-content-around">Sport</label>
                  <input type="range" class="custom-range" name="trip[criteria][sport]" min="0" max="100" step="1" id="sport">
                </div>
                <div class="form-group  form-control-label">
                  <label for="culture" class="d-flex justify-content-around">Culture</label>
                  <input type="range" class="custom-range" name="trip[criteria][culture]" min="0" max="100" step="1" id="culture">
                </div>
                <div class="form-group  form-control-label">
                  <label for="visit" class="d-flex justify-content-around">Visit</label>
                  <input type="range" class="custom-range" name="trip[criteria][visit]" min="0" max="100" step="1" id="visit">
                </div>
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary rounded" data-dismiss="modal">Close</button>
          <%= f.button :submit,class: "btn green-btn-criteria" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- fin modal -->
<!-- début modal 2  -->
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
        <div class="text-center trip-header-new">Personnalize your trip</div>
        </h5>
      </div>
      <div class="modal-body">
        <div class="form-container-criteria-slider" id="preferences" >
          <div class="d-flex justify-content-center pb-4">
            <div class="col-md-7 mt-6">
              <%= simple_form_for@trip, method: :patch, url: preferences_trip_path do |f| %>
              <div class="d-flex justify-content-around mb-8">
                <div class="form-group pr-4 form-control-label">
                  <label for="party" class="d-flex justify-content-around">Party</label>
                  <input type="range" class="custom-range" name="trip[criteria][party]" min="0" max="100" step="1" id="party" >
                </div>
         <!--        <div class="form-group pl-4 form-control-label">
                  <label for="sport" class="d-flex justify-content-around">Sport</label>
                  <input type="range" class="custom-range" name="trip[criteria][sport]" min="0" max="100" step="1" id="sport">
                </div>
              </div>
              <div class="d-flex justify-content-around ">
                <div class="form-group pr-4 form-control-label">
                  <label for="culture" class="d-flex justify-content-around">Culture</label>
                  <input type="range" class="custom-range" name="trip[criteria][culture]" min="0" max="100" step="1" id="culture">
                </div>
                <div class="form-group pl-4 form-control-label">
                  <label for="visit" class="d-flex justify-content-around">Visit</label>
                  <input type="range" class="custom-range" name="trip[criteria][visit]" min="0" max="100" step="1" id="visit">
                </div> -->
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit,class: "btn green-btn-criteria" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- fin modal 2 -->
    <%= javascript_pack_tag 'rangesliders_pack' %>

app/views/trips/edit.html.erb
 <div class="form-container form-border">
   <div class="tabs-container">
     <div class="tab-button tab-active">1</div>
     <hr>
     <div class="tab-button">2</div>
     <hr>
     <div class="tab-button">3</div>
   </div>
    <h1 class="mb-4 text-center">Choose preferences</h1>
    <div class="d-flex justify-content-center">
      <div class="col-md-6 mt-8">
        <form action="/trips/<%= @trip.id %>" method="post">
          <input name="_method" type="hidden" value="patch" />
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group">
            <label for="beach">Beach</label>
            <input type="text" class="form-control" id="beach" name="trip[criteria][beach]" placeholder="20%">
          </div>
          <div class="form-group">
            <label for="sport">Sport</label>
            <input type="text" class="form-control" id="sport" name="trip[criteria][sport]"placeholder="20%">
          </div>
          <div class="form-group">
            <label for="culture">Culture</label>
            <input type="text" class="form-control" id="culture" name="trip[criteria][culture]"placeholder="20%">
          </div>
          <div class="form-group">
            <label for="visit">Visit</label>
            <input type="text" class="form-control" id="visit" name="trip[criteria][visit]"placeholder="20%">
          </div>

            <button type="submit" class="green-btn">Next</button>
        </form>
      </div>
    </div>

</div>

app/views/trips/index.html.erb
<div class="container-fullscreen">
  <h2 class="trip-header text-center pt-6">List of your trips</h2>
  <div class="trip-index-container">
    <h5>My trips ( <%= @trips.count %> )</h5>
    <% @trips.reverse.each do |trip| %>
    <%= link_to details_trip_path (trip) do%>
    <div class="card-trip mb-6" id="index-pics">
      <p class="absolute type-activity index-trip"><%= trip.arrival_city.name %> to <%= trip.departure_city.name %></p>
      <%= image_tag(trip.steps.first.activities.first.photo) %>
      <div class="card-trip-infos index-trip index-trip-bottom">
         <p><%=  trip.end_date.to_formatted_s(:short).to_i - trip.start_date.to_formatted_s(:short).to_i %> Days Trip</p>
         <div class="d-flex index-trip index-trip-bottom">
         <p> From <%= trip.start_date.to_formatted_s(:short) %></p>
         <p class="pl-4"> To <%= trip.end_date.to_formatted_s(:short) %></p>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
<!--
<div class="mb-10">
  <% @trips.reverse.each do |trip| %>

  <% trip.steps.each do |step| %>
      <%= link_to details_trip_path (trip) do%>

  <p>Find a place to stay in <%= step.city.name %></p>

  <% end %>
  <% end %>
  <% end %>
  </div>
 -->

</div>

app/views/trips/mistery.html.erb
<div class="container-fullscreen">
  <div class="form-container-criteria-slider ">
    <h2 class="mb-4 text-center trip-header">Choose your mystery level</h2>
    <div class="tabs-container mt-3">
      <div class="tab-button">1</div>
      <hr>
      <div class="tab-button">2</div>
      <hr>
      <div class="tab-button">3</div>
      <hr>
      <div class="tab-button tab-active" id="go-button">Go</div>
    </div>
    <div class="d-flex justify-content-center">
      <div class="container mt-3">
        <!-- Planning 1 -->
        <%= simple_form_for @trip, :url => change_mistery_trip_path(@trip), :method => :patch do |f| %>
        <!-- Inject fixed activities -->
        <!-- slider if no activities to choose -->
        <!-- culture to choose -->
        <div class="mistery-choices">
          <div class="mistery-choices-row-three">
            <div class="form-group">
              <!-- <input type="hidden" name="activities_ids[]" value=""> -->
              <!-- <div class="activity-choices"> -->
              <div class="card col-sm-8 mb-5 parent-class-mistery margin-none padding-none card-mistery">
                <input type="checkbox"class="hidden check-mistery" value="0" name="trip[percentage_of_mistery]" id="mistery-percentage-zero">
                <label for="mistery-percentage-zero" class="activity-choice mistery-choice card-title margin-none pb-2">
                  <%= image_tag 'dome.png', class: "card-img-top" %>
                  <div class="mt-2"> No mystery </div>
                </label>
              </div>
            </div>
            <div class="form-group">
              <!-- <input type="hidden" name="activities_ids[]" value=""> -->
              <!-- <div class="activity-choices"> -->
              <div class="card col-sm-8 mb-5 parent-class-mistery margin-none padding-none card-mistery" >
                <input type="checkbox"class="hidden check-mistery" value="25" name="trip[percentage_of_mistery]" id="mistery-percentage-25">
                <label for="mistery-percentage-25" class="activity-choice mistery-choice card-title margin-none pb-2">
                  <%= image_tag 'dome25.png', class: "card-img-top" %>
                  <div class="mt-2"> 25% of mystery </div>
                </label>
              </div>
            </div>
            <div class="form-group">
              <!-- <input type="hidden" name="activities_ids[]" value=""> -->
              <!-- <div class="activity-choices"> -->
              <div class="card col-sm-8 mb-5 parent-class-mistery margin-none padding-none card-mistery" >
                <input type="checkbox"class="hidden check-mistery" value="50" name="trip[percentage_of_mistery]" id="mistery-percentage-50">
                <label for="mistery-percentage-50" class="activity-choice mistery-choice card-title margin-none pb-2">
                  <%= image_tag 'dome50.png', class: "card-img-top" %>
                  <div class="mt-2"> 50% of mystery</div>
                </label>
              </div>
            </div>
          </div>
          <div class="mistery-choices-row-two">
            <div class="form-group">
              <!-- <input type="hidden" name="activities_ids[]" value=""> -->
              <!-- <div class="activity-choices"> -->
              <div class="card  mb-5 parent-class-mistery margin-none card-between-cards imposed-width card-mistery">
                <input type="checkbox"class="hidden check-mistery" value="75" name="trip[percentage_of_mistery]" id="mistery-percentage-75">
                <label for="mistery-percentage-75" class="activity-choice mistery-choice card-title margin-none pb-2 card-mistery">
                  <%= image_tag 'dome75.png', class: "card-img-top" %>
                  <div class="mt-2"> 75% of mystery </div>
                </label>
              </div>
            </div>
            <div class="form-group">
              <!-- <input type="hidden" name="activities_ids[]" value=""> -->
              <!-- <div class="activity-choices"> -->
              <div class="card  mb-5 parent-class-mistery margin-none imposed-width card-mistery">
                <input type="checkbox"class="hidden check-mistery" value="100" name="trip[percentage_of_mistery]" id="mistery-percentage-100">
                <label for="mistery-percentage-100" class="activity-choice mistery-choice card-title margin-none pb-2">
                  <%= image_tag 'dome100.png', class: "card-img-top" %>
                  <div class="mt-2"> Total mystery </div>
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="fix-button-position">
          <%= f.submit "Go", class: "btn green-btn btn-position"  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>