config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :trips do
    member do
      patch :preferences
      get :details
      patch :save
      get :mistery
      patch :change_mistery
    end
    resources :steps, only: ['create', 'new']
  end
  resources :steps, only: ['index', 'show']
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  Made with <i class="fas fa-heart"></i> by Tripper's team
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top" id="tripper_navbar"><div class="no-border">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "tripper_logo.png",style: "width:120px"%>
  </div>

  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "My trips", trips_path, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to "New trip", new_trip_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <%= image_tag 'jr.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, render: root_path, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
      <% end %>
    </ul>
  </div>
</div>